name: Man10GambleBar
version: '1.0'
main: yusama125718.man10GambleBar.Man10GambleBar
api-version: '1.20'

commands:
  mgbar:
    description: Man10GambleBar

permissions:
  mgbar.op:
    default: op
  mgbar.p:
    default: true